//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool.
// Code is generated on: 23/12/2009 3:08:03
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace TutorialEntities
{

    /// <summary>
    /// There are no comments for TutorialEntities.Articulo in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TutorialEntities", Name="Articulo")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Articulo : global::System.Data.Objects.DataClasses.EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new Articulo object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        public static Articulo CreateArticulo(string id)
        {
            Articulo articulo = new Articulo();
            articulo.Id = id;
            return articulo;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                string value = this._Id;
                OnGetId(ref value);
                return value;
            }
            set
            {
                this.OnIdChanging(ref value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private string _Id;
        partial void OnGetId(ref string value);
        partial void OnIdChanging(ref string value);
        partial void OnIdChanged();
    
        /// <summary>
        /// There are no comments for Descripcion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                string value = this._Descripcion;
                OnGetDescripcion(ref value);
                return value;
            }
            set
            {
                this.OnDescripcionChanging(ref value);
                this.ReportPropertyChanging("Descripcion");
                this._Descripcion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Descripcion");
                this.OnDescripcionChanged();
            }
        }
        private string _Descripcion;
        partial void OnGetDescripcion(ref string value);
        partial void OnDescripcionChanging(ref string value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// There are no comments for CantPalletCompleto in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> CantPalletCompleto
        {
            get
            {
                global::System.Nullable<long> value = this._CantPalletCompleto;
                OnGetCantPalletCompleto(ref value);
                return value;
            }
            set
            {
                this.OnCantPalletCompletoChanging(ref value);
                this.ReportPropertyChanging("CantPalletCompleto");
                this._CantPalletCompleto = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CantPalletCompleto");
                this.OnCantPalletCompletoChanged();
            }
        }
        private global::System.Nullable<long> _CantPalletCompleto;
        partial void OnGetCantPalletCompleto(ref global::System.Nullable<long> value);
        partial void OnCantPalletCompletoChanging(ref global::System.Nullable<long> value);
        partial void OnCantPalletCompletoChanged();

        #endregion

        #region Navigation Properties

        /// <summary>
        /// There are no comments for Pallet in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TutorialEntities", "Articulo_Pallet", "Pallets")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Pallet> Pallets
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Pallet>("TutorialEntities.Articulo_Pallet", "Pallets");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Pallet>("TutorialEntities.Articulo_Pallet", "Pallets", value);
                }
            }
        }

        #endregion
    }

}
