//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool.
// Code is generated on: 18/12/2009 01:21:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace TutorialEntities
{

    /// <summary>
    /// There are no comments for TutorialEntities.Sedan in the schema.
    /// </summary>
    /// <KeyProperties>
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TutorialEntities", Name="Sedan")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Sedan : Automovil
    {
        #region Factory Method

        /// <summary>
        /// Create a new Sedan object.
        /// </summary>
        /// <param name="cilindrada">Initial value of Cilindrada.</param>
        /// <param name="marca">Initial value of Marca.</param>
        /// <param name="modelo">Initial value of Modelo.</param>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="cantidadPuertas">Initial value of CantidadPuertas.</param>
        /// <param name="capacidadBaul">Initial value of CapacidadBaul.</param>
        public static Sedan CreateSedan(int cilindrada, string marca, string modelo, long id, int cantidadPuertas, int capacidadBaul)
        {
            Sedan sedan = new Sedan();
            sedan.Cilindrada = cilindrada;
            sedan.Marca = marca;
            sedan.Modelo = modelo;
            sedan.Id = id;
            sedan.CantidadPuertas = cantidadPuertas;
            sedan.CapacidadBaul = capacidadBaul;
            return sedan;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for CapacidadBaul in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CapacidadBaul
        {
            get
            {
                int value = this._CapacidadBaul;
                OnGetCapacidadBaul(ref value);
                return value;
            }
            set
            {
                this.OnCapacidadBaulChanging(ref value);
                this.ReportPropertyChanging("CapacidadBaul");
                this._CapacidadBaul = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CapacidadBaul");
                this.OnCapacidadBaulChanged();
            }
        }
        private int _CapacidadBaul;
        partial void OnGetCapacidadBaul(ref int value);
        partial void OnCapacidadBaulChanging(ref int value);
        partial void OnCapacidadBaulChanged();

        #endregion
    }

}
