//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool.
// Code is generated on: 23/12/2009 3:08:03
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace TutorialEntities
{

    /// <summary>
    /// There are no comments for TutorialEntities.Gerente in the schema.
    /// </summary>
    /// <KeyProperties>
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TutorialEntities", Name="Gerente")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Gerente : Persona
    {
        #region Factory Method

        /// <summary>
        /// Create a new Gerente object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="cargo">Initial value of Cargo.</param>
        public static Gerente CreateGerente(long id, string cargo)
        {
            Gerente gerente = new Gerente();
            gerente.Id = id;
            gerente.Cargo = cargo;
            return gerente;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for Cargo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo
        {
            get
            {
                string value = this._Cargo;
                OnGetCargo(ref value);
                return value;
            }
            set
            {
                this.OnCargoChanging(ref value);
                this.ReportPropertyChanging("Cargo");
                this._Cargo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Cargo");
                this.OnCargoChanged();
            }
        }
        private string _Cargo;
        partial void OnGetCargo(ref string value);
        partial void OnCargoChanging(ref string value);
        partial void OnCargoChanged();

        #endregion
    }

}
