//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool.
// Code is generated on: 23/12/2009 3:08:03
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace TutorialEntities
{

    /// <summary>
    /// There are no comments for TutorialEntities.Moto in the schema.
    /// </summary>
    /// <KeyProperties>
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TutorialEntities", Name="Moto")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Moto : Vehiculo
    {
        #region Factory Method

        /// <summary>
        /// Create a new Moto object.
        /// </summary>
        /// <param name="cilindrada">Initial value of Cilindrada.</param>
        /// <param name="marca">Initial value of Marca.</param>
        /// <param name="modelo">Initial value of Modelo.</param>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="encendidoElectronico">Initial value of EncendidoElectronico.</param>
        public static Moto CreateMoto(int cilindrada, string marca, string modelo, long id, string encendidoElectronico)
        {
            Moto moto = new Moto();
            moto.Cilindrada = cilindrada;
            moto.Marca = marca;
            moto.Modelo = modelo;
            moto.Id = id;
            moto.EncendidoElectronico = encendidoElectronico;
            return moto;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for EncendidoElectronico in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string EncendidoElectronico
        {
            get
            {
                string value = this._EncendidoElectronico;
                OnGetEncendidoElectronico(ref value);
                return value;
            }
            set
            {
                this.OnEncendidoElectronicoChanging(ref value);
                this.ReportPropertyChanging("EncendidoElectronico");
                this._EncendidoElectronico = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("EncendidoElectronico");
                this.OnEncendidoElectronicoChanged();
            }
        }
        private string _EncendidoElectronico;
        partial void OnGetEncendidoElectronico(ref string value);
        partial void OnEncendidoElectronicoChanging(ref string value);
        partial void OnEncendidoElectronicoChanged();

        #endregion
    }

}
