//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool.
// Code is generated on: 18/12/2009 01:21:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace TutorialEntities
{

    /// <summary>
    /// There are no comments for TutorialEntities.LiderTecnico in the schema.
    /// </summary>
    /// <KeyProperties>
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TutorialEntities", Name="LiderTecnico")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class LiderTecnico : Desarrollador
    {
        #region Factory Method

        /// <summary>
        /// Create a new LiderTecnico object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="nivel">Initial value of Nivel.</param>
        /// <param name="projecto">Initial value of Projecto.</param>
        public static LiderTecnico CreateLiderTecnico(long id, string nivel, string projecto)
        {
            LiderTecnico liderTecnico = new LiderTecnico();
            liderTecnico.Id = id;
            liderTecnico.Nivel = nivel;
            liderTecnico.Projecto = projecto;
            return liderTecnico;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for Projecto in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Projecto
        {
            get
            {
                string value = this._Projecto;
                OnGetProjecto(ref value);
                return value;
            }
            set
            {
                this.OnProjectoChanging(ref value);
                this.ReportPropertyChanging("Projecto");
                this._Projecto = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Projecto");
                this.OnProjectoChanged();
            }
        }
        private string _Projecto;
        partial void OnGetProjecto(ref string value);
        partial void OnProjectoChanging(ref string value);
        partial void OnProjectoChanged();

        #endregion
    }

}
