//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool.
// Code is generated on: 11/12/2009 05:17:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace TutorialEntities
{

    /// <summary>
    /// There are no comments for TutorialEntities.Automovil in the schema.
    /// </summary>
    /// <KeyProperties>
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TutorialEntities", Name="Automovil")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Automovil : Vehiculo
    {
        #region Factory Method

        /// <summary>
        /// Create a new Automovil object.
        /// </summary>
        /// <param name="peso">Initial value of Peso.</param>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="cantPuertas">Initial value of CantPuertas.</param>
        public static Automovil CreateAutomovil(int peso, long id, int cantPuertas)
        {
            Automovil automovil = new Automovil();
            automovil.Peso = peso;
            automovil.Id = id;
            automovil.CantPuertas = cantPuertas;
            return automovil;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for CantPuertas in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CantPuertas
        {
            get
            {
                int value = this._CantPuertas;
                OnGetCantPuertas(ref value);
                return value;
            }
            set
            {
                this.OnCantPuertasChanging(ref value);
                this.ReportPropertyChanging("CantPuertas");
                this._CantPuertas = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CantPuertas");
                this.OnCantPuertasChanged();
            }
        }
        private int _CantPuertas;
        partial void OnGetCantPuertas(ref int value);
        partial void OnCantPuertasChanging(ref int value);
        partial void OnCantPuertasChanged();

        #endregion
    }

}
