//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool.
// Code is generated on: 23/12/2009 3:08:03
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace TutorialEntities
{

    /// <summary>
    /// There are no comments for TutorialEntities.Pasante in the schema.
    /// </summary>
    /// <KeyProperties>
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TutorialEntities", Name="Pasante")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Pasante : Desarrollador
    {
        #region Factory Method

        /// <summary>
        /// Create a new Pasante object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="nivel">Initial value of Nivel.</param>
        /// <param name="universidad">Initial value of Universidad.</param>
        public static Pasante CreatePasante(long id, string nivel, string universidad)
        {
            Pasante pasante = new Pasante();
            pasante.Id = id;
            pasante.Nivel = nivel;
            pasante.Universidad = universidad;
            return pasante;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for Universidad in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Universidad
        {
            get
            {
                string value = this._Universidad;
                OnGetUniversidad(ref value);
                return value;
            }
            set
            {
                this.OnUniversidadChanging(ref value);
                this.ReportPropertyChanging("Universidad");
                this._Universidad = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Universidad");
                this.OnUniversidadChanged();
            }
        }
        private string _Universidad;
        partial void OnGetUniversidad(ref string value);
        partial void OnUniversidadChanging(ref string value);
        partial void OnUniversidadChanged();

        #endregion
    }

}
