//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool.
// Code is generated on: 11/12/2009 05:17:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace TutorialEntities
{

    /// <summary>
    /// There are no comments for TutorialEntities.Vehiculo in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TutorialEntities", Name="Vehiculo")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public abstract partial class Vehiculo : global::System.Data.Objects.DataClasses.EntityObject
    {

        #region Properties
    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                long value = this._Id;
                OnGetId(ref value);
                return value;
            }
            set
            {
                this.OnIdChanging(ref value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private long _Id;
        partial void OnGetId(ref long value);
        partial void OnIdChanging(ref long value);
        partial void OnIdChanged();
    
        /// <summary>
        /// There are no comments for Peso in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Peso
        {
            get
            {
                int value = this._Peso;
                OnGetPeso(ref value);
                return value;
            }
            set
            {
                this.OnPesoChanging(ref value);
                this.ReportPropertyChanging("Peso");
                this._Peso = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Peso");
                this.OnPesoChanged();
            }
        }
        private int _Peso;
        partial void OnGetPeso(ref int value);
        partial void OnPesoChanging(ref int value);
        partial void OnPesoChanged();
    
        /// <summary>
        /// There are no comments for Descripcion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                string value = this._Descripcion;
                OnGetDescripcion(ref value);
                return value;
            }
            set
            {
                this.OnDescripcionChanging(ref value);
                this.ReportPropertyChanging("Descripcion");
                this._Descripcion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Descripcion");
                this.OnDescripcionChanged();
            }
        }
        private string _Descripcion;
        partial void OnGetDescripcion(ref string value);
        partial void OnDescripcionChanging(ref string value);
        partial void OnDescripcionChanged();

        #endregion
    }

}
