//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool.
// Code is generated on: 11/12/2009 05:17:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace TutorialEntities
{

    /// <summary>
    /// There are no comments for TutorialEntities.Scooter in the schema.
    /// </summary>
    /// <KeyProperties>
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TutorialEntities", Name="Scooter")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Scooter : Moto
    {
        #region Factory Method

        /// <summary>
        /// Create a new Scooter object.
        /// </summary>
        /// <param name="peso">Initial value of Peso.</param>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="encPedal">Initial value of EncPedal.</param>
        /// <param name="spoiler">Initial value of Spoiler.</param>
        public static Scooter CreateScooter(int peso, long id, string encPedal, string spoiler)
        {
            Scooter scooter = new Scooter();
            scooter.Peso = peso;
            scooter.Id = id;
            scooter.EncPedal = encPedal;
            scooter.Spoiler = spoiler;
            return scooter;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for Spoiler in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Spoiler
        {
            get
            {
                string value = this._Spoiler;
                OnGetSpoiler(ref value);
                return value;
            }
            set
            {
                this.OnSpoilerChanging(ref value);
                this.ReportPropertyChanging("Spoiler");
                this._Spoiler = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Spoiler");
                this.OnSpoilerChanged();
            }
        }
        private string _Spoiler;
        partial void OnGetSpoiler(ref string value);
        partial void OnSpoilerChanging(ref string value);
        partial void OnSpoilerChanged();

        #endregion
    }

}
