//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool.
// Code is generated on: 18/12/2009 01:21:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace TutorialEntities
{

    /// <summary>
    /// There are no comments for TutorialEntities.Automovil in the schema.
    /// </summary>
    /// <KeyProperties>
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TutorialEntities", Name="Automovil")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public abstract partial class Automovil : Vehiculo
    {

        #region Properties
    
        /// <summary>
        /// There are no comments for CantidadPuertas in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadPuertas
        {
            get
            {
                int value = this._CantidadPuertas;
                OnGetCantidadPuertas(ref value);
                return value;
            }
            set
            {
                this.OnCantidadPuertasChanging(ref value);
                this.ReportPropertyChanging("CantidadPuertas");
                this._CantidadPuertas = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CantidadPuertas");
                this.OnCantidadPuertasChanged();
            }
        }
        private int _CantidadPuertas;
        partial void OnGetCantidadPuertas(ref int value);
        partial void OnCantidadPuertasChanging(ref int value);
        partial void OnCantidadPuertasChanged();

        #endregion
    }

}
