//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool.
// Code is generated on: 18/12/2009 01:21:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace TutorialEntities
{

    /// <summary>
    /// There are no comments for TutorialEntities.Camioneta in the schema.
    /// </summary>
    /// <KeyProperties>
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TutorialEntities", Name="Camioneta")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Camioneta : Automovil
    {
        #region Factory Method

        /// <summary>
        /// Create a new Camioneta object.
        /// </summary>
        /// <param name="cilindrada">Initial value of Cilindrada.</param>
        /// <param name="marca">Initial value of Marca.</param>
        /// <param name="modelo">Initial value of Modelo.</param>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="cantidadPuertas">Initial value of CantidadPuertas.</param>
        /// <param name="capacidadCaja">Initial value of CapacidadCaja.</param>
        public static Camioneta CreateCamioneta(int cilindrada, string marca, string modelo, long id, int cantidadPuertas, int capacidadCaja)
        {
            Camioneta camioneta = new Camioneta();
            camioneta.Cilindrada = cilindrada;
            camioneta.Marca = marca;
            camioneta.Modelo = modelo;
            camioneta.Id = id;
            camioneta.CantidadPuertas = cantidadPuertas;
            camioneta.CapacidadCaja = capacidadCaja;
            return camioneta;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for CapacidadCaja in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CapacidadCaja
        {
            get
            {
                int value = this._CapacidadCaja;
                OnGetCapacidadCaja(ref value);
                return value;
            }
            set
            {
                this.OnCapacidadCajaChanging(ref value);
                this.ReportPropertyChanging("CapacidadCaja");
                this._CapacidadCaja = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CapacidadCaja");
                this.OnCapacidadCajaChanged();
            }
        }
        private int _CapacidadCaja;
        partial void OnGetCapacidadCaja(ref int value);
        partial void OnCapacidadCajaChanging(ref int value);
        partial void OnCapacidadCajaChanged();

        #endregion
    }

}
